import { NextIntlClientProvider } from 'next-intl';

import { notFound } from 'next/navigation';

import Script from 'next/script';

import Navbar from '@/components/navbar';
import Footer from '@/components/footer';
import CookieConsent from '@/components/cookie';

import type { Metadata } from 'next';

import '@fontsource-variable/inter';

import '@fontsource/fira-sans/800.css';

import '../globals.scss';

import locales from '../../locales.json';

export function generateStaticParams(): Array<{ locale: string }> {
  return locales.map(((locale: string): { locale: string } => ({
    locale: locale
  })));
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default async function RootLayout({
  children,
  params: {
    locale
  }
}: {
  children: React.ReactNode,
  params: any
}) {

  let messages;
  try {
    messages = (await import(`../../i18n/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
 
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar />
          { children }
          <Footer />
          <CookieConsent />
        </NextIntlClientProvider>
        <Script async defer data-website-id="1ee45743-c0ed-4629-a622-b2c1185eed45" src="https://umami.krahforst.dev/umami.js" />
        <Script src="https://www.googletagmanager.com/gtag/js?id=G-NQRESZGTVC" />
        <Script id="google-analytics">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
  
            gtag('config', 'G-NQRESZGTVC');
          `}
        </Script>
      </body>
    </html>
  );
};